### ISSUE TITLE
this is amazing; thanks

### ISSUE THREAD

**Issue by timelyportfolio** [PitchInteractiveInc/hexagon-cartograms#24]
Not an issue, just praise and recognition.  Thanks so much for putting this together.  Lovely!

**Comment by adamflorin** [comment]
@timelyportfolio Thanks! We're still refining it. Stay tuned for an announcement when it's ready!

**Comment by timelyportfolio** [comment]
My geo abilities are limited, but please let me know if I can help.  I'd love to be able to tie this into R.
