### ISSUE TITLE
Issue with NPR 1-on-1 export

### ISSUE THREAD

**Issue by MartinLBarron** [PitchInteractiveInc/hexagon-cartograms#60]
I think there may be a bug in the export of the npr 1-on-1.  I can map it correctly but I get the map below, which seems to shift every other row of tiles.

![rplot04](https://cloud.githubusercontent.com/assets/5630294/18938515/a7d47d02-85be-11e6-8f2c-57e0bf1e5ae5.png)

It's certainly possible that I'm doing something wrong in my import and plotting.  But when I look at the raw coordinates for two states (WA and ID) I don't see any points in common, but would expect 2 points to be in common.

Washington
        [
      [
        213.2549573248839,
        190.28070175438597
      ],
      [
        232.64177162714606,
        179.08771929824562
      ],
      [
        252.02858592940822,
        190.28070175438597
      ],
      [
        252.02858592940822,
        212.66666666666669
      ],
      [
        232.64177162714606,
        223.85964912280704
      ],
      [
        213.2549573248839,
        212.66666666666669
      ],
      [
        213.2549573248839,
        190.28070175438597
      ]

Idaho
    [
      [
        271.4154002316704,
        156.7017543859649
      ],
      [
        290.80221453393256,
        145.50877192982455
      ],
      [
        310.1890288361947,
        156.7017543859649
      ],
      [
        310.1890288361947,
        179.08771929824562
      ],
      [
        290.80221453393256,
        190.28070175438597
      ],
      [
        271.4154002316704,
        179.08771929824562
      ],
      [
        271.4154002316704,
        156.7017543859649
      ]
    ],

**Comment by adamflorin** [comment]
@MartinLBarron Yes, we've discovered that an off-by-one bug we thought we had squashed in TopoJSON export has crept back in. Our plan is to fix this before the weekend. Will keep you updated here!

**Comment by rogerfischer** [comment]
Might be the same problem here:
On Tilegram (https://pitchinteractiveinc.github.io/tilegrams/)
<img width="1068" alt="tilegram_screenshot" src="https://cloud.githubusercontent.com/assets/7697124/18976836/19324186-866a-11e6-83da-ba8bcf00a012.png">
TopoJSON output:
<img width="1257" alt="mapshaper_screenshot" src="https://cloud.githubusercontent.com/assets/7697124/18976834/12eeb49e-866a-11e6-9ac7-5444fa605193.png">

**Comment by adamflorin** [comment]
@MartinLBarron @rogerfischer This issue is now fixed. There were symmetric arithmetic errors in the import and export processes, so that tilegrams which looked correct in our editor were actually being stored incorrectly as TopoJSON.

If you have any old tilegram TopoJSON that you have put time into and would like to fix, the solution will be, in short, to load it, select every other row using the marquee, and push it to the right or left. If you're having any trouble, let us know and we'll help as we can.

Many thanks for your patience and for letting us know!

**Comment by rogerfischer** [comment]
Hi, 
I didn't close the editor, so I got it out as in the Editor. Thanks for that!
It now works as intended.

Now I have a new problem!
When I export the TopoJSON and try load it in d3, there is a lot of transforming I have to do. 

When I start out in d3, the topoJSON looks like this:
<img width="931" alt="screen shot 2016-09-30 at 1 18 02 pm" src="https://cloud.githubusercontent.com/assets/7697124/19005632/74f037c0-8710-11e6-9753-0559d36977ac.png">
After moult scaling and translating, I arrive at something like this (mirror inversed and upside down  and not fully hexagonal):
<img width="853" alt="screen shot 2016-09-30 at 1 17 15 pm" src="https://cloud.githubusercontent.com/assets/7697124/19005666/a89a1d5c-8710-11e6-8a39-dfd031dafa6b.png">

Any tips what to do from the moment I export the file?
Best
Roger

**Comment by rogerfischer** [comment]
Solved :) With geoTransform, geoStream and some affine matrix transformations
