### ISSUE TITLE
Exported TopoJSON has no statenames

### ISSUE THREAD

**Issue by bhaskarvk** [PitchInteractiveInc/hexagon-cartograms#64]
It would be nice to have the state names and ISO 2 & 3 digit codes in the exported topojson.

**Comment by adamflorin** [comment]
That's a good call, we'll get on that.

**Comment by nthitz** [comment]
@bhaskarvk two letter state codes are now included in the properties object of each tile. For maps that you created before this change, the `id` attribute of each tile was the US FIPS code of that state. You can find a full list of FIPS codes here https://www.mcc.co.mercer.pa.us/dps/state_fips_code_listing.htm If you upload your existing tilegram topojson files and then reexport, they _should_ have the state abbreviations included too

**Comment by bhaskarvk** [comment]
Cool, thanks much!

**Comment by bhaskarvk** [comment]
I made a R package from your tilegrams. https://github.com/bhaskarvk/tilegramsR.
