### ISSUE TITLE
Feature Request: More Tilegrams

### ISSUE THREAD

**Issue by bhaskarvk** [PitchInteractiveInc/hexagon-cartograms#67]
Here are a few more interesting tiles worthy of including in this awesome package
- [ ] WP https://www.washingtonpost.com/graphics/politics/2016-election/50-state-poll/
- [ ] WSJ http://graphics.wsj.com/elections/2016/2016-electoral-college-map-predictions/
- [ ] NPR http://www.npr.org/2016/08/16/490103767/npr-battleground-map-hillary-clinton-solidifies-lead-against-donald-trump
- [ ] Daily Kos http://elections.dailykos.com/app/elections/2016/office/president (Click on Cartogram link)

**Comment by bhaskarvk** [comment]
If it helps I already made some progress converting the WP and NPR SVGs to WKT and subsequently to GeoJSONs, but only the geometry not the features w/o which the GeoJSON is of not much use.
Let me know if you still want them.

**Comment by adamflorin** [comment]
Thanks for this round-up, @bhaskarvk!

We love those maps but unfortunately, for different reasons, Tilegrams isn't able to represent any of them—yet.

We actually [tried](https://twitter.com/adamflorin/status/782987087192526848) with the Daily Kos one, but it has so many tiles that it makes Tilegrams run a bit slowly on older computers. We hope to perform some optimizations at some point and try again.

The WP and WSJ ones are both rectangular in shape, and Tilegrams only supports hexagons—pointy-topped ones at that! One day soon we would like to support all repeating geometries, including triangles, which we [used](http://pitchinteractive.com/work/WorldOfMen.html) in a project a few years back.

Lastly, the NPR map is the only one of those four which we don't plan on supporting, as it is of a different sort—specifically, it's a [Dorling cartogram](https://www.arcgis.com/home/item.html?id=b686a7679cb747e9825d1d1bb6b26046), whereas Tilegrams is only for cartograms which conform to a tiled grid.

Thanks also for your R integration, we're very excited to see your progress!

**Comment by bhaskarvk** [comment]
Thanks for the info @adamflorin. Feel free to close this if you want, or keep it open for your tracking purposes.
And Thank You for such a awesome project.

**Comment by adamflorin** [comment]
I think we should keep it open to remind ourselves how much we want to support other repeating geometries and larger maps. ;) Also, it can be a nice place to keep track of other tilegrams as they come up…
