### ISSUE TITLE
Is there a documentation to on board other maps?

### ISSUE THREAD

**Issue by addu390** [PitchInteractiveInc/hexagon-cartograms#92]
I'm planning to onboard the world map, looking at the code and reference PRs; the only doubt I have are:

- The `topo.json` in the `maps` folder is the original map?
- How do I generate the tilegram in `tilegrams` for a population-scaled world map?

All the other necessary datasets are readily available, the country code, population count, and it's only a matter of converting them to the correct format. Just a clarification on what the `topo` in `maps` and `tilegrams` would look like?

**Comment by nthitz** [comment]
https://github.com/PitchInteractiveInc/tilegrams/pull/85 has an example of adding a new map.

You are correct on the topo.json file, that should be a topojson map file that you want to create in this case a world map. The file in the tilegrams folder is created from using the Topojson export function once you have used the tool to create your map.

FWIW we had attempted to create a world map tilegram in the past but didn't pursue it too far. Given the wide distribution both of country land areas and populations, our tool struggles a bit to create a world map that is a very accurate representation of the countries. Having said that, please let us know if you come up with something on your own!

**Comment by addu390** [comment]
The #85 is a good example than the one I referred to; thank you. I'll check it out and try generating a tiregram that preserves the shape of countries.

**Comment by addu390** [comment]
@nthitz You were right about the world map tilegram not visually appealing. So, I built an elementary hex tool: https://www.pyblog.xyz/population-cartogram/

Which got me thinking, how do "tilegrams" work? What's the logic of scaling countries/states based on a metric like population? Where do I start in the codebase to understand this section and any papers for the same would be of tremendous help.

**Comment by addu390** [comment]
@nthitz You were right about Tilegrams not showing a visually pleasing representation of the world cartogram, mostly because of the resolution and an issue with the topogram library. However, I build a lightweight version here: [https://www.pyblog.xyz/population-cartogram/](https://www.pyblog.xyz/population-cartogram/). And you can close the issue if you'd like.
